Films/Controllers/ActorsController.cs
using Films.Kernel.Context;
using Films.Kernel.Managers.Managers;
using Films.Server.Controllers;

namespace Films.Server.Views.Films
{
    public class ActorsController : BaseController<ActorsManager, Actor>
    {
        public override string Tag => "ActorsController";
    }
}

Films/Controllers/BaseController.cs
using Films.Kernel.Context;
using Films.Kernel.Managers;
using Films.Kernel.Managers.Base;
using Films.Kernel.Managers.Logging;
using System;
using System.Web.Mvc;

namespace Films.Server.Controllers
{
    public abstract class BaseController<TManager, TDataType> : Controller where TManager : BaseManager<TDataType>, new() where TDataType : BaseModel, new()
    {
        public abstract string Tag { get; }

        protected ManagerFactory _factory;
        protected BaseManager<TDataType> _manager;
        protected Log _log;

        public BaseController() : this(Injector.CreateLog())
        {
            _factory = ManagerFactory.Instance;
            _manager = _factory.Create<TManager>();
        }
        public BaseController(Log log)
        {
            _log = log;
        }

        [HttpGet]
        public virtual ActionResult Index()
        {
            return WViewRequest($"Get all elements.", () =>
            {
                return View(_manager.GetAll());
            });
        }

        [HttpGet]
        public virtual ActionResult Create()
        {
            return WViewRequest($"Create new element.", () =>
            {
                var element = new TDataType();

                return View("Edit", element);
            });
        }

        [HttpGet]
        public virtual ActionResult Edit(long id)
        {
            return WViewRequest($"Edit element #{id}.", () =>
            {
                var model = Find("Edit", id);

                return View(model);
            });
        }

        [HttpGet]
        public virtual ActionResult Details(long id)
        {
            return WViewRequest($"Details for element #{id}.", () =>
            {
                var model = Find("Details", id);

                return View(model);
            });
        }

        [HttpGet]
        public virtual ActionResult Remove(long id)
        {
            return WViewRequest($"Remove element #{id}", () =>
            {
                _manager.Remove(id);

                return RedirectIndex();
            });
        }
        [HttpPost]
        public virtual ActionResult Update(TDataType element)
        {
            return WViewRequest($"Update element #{element.Id}", () =>
            {
                var model = _manager.Find(element.Id);

                if (null != model)
                {
                    _manager.Update(element);
                }
                else
                {
                    _manager.Add(element);
                }


                return RedirectIndex();
            });
        }

        protected TDataType Find(string action, long id)
        {
            var model = _manager.Find(id);

            if (null == model)
            {
                throw new InvalidRequestException($"{action}: element with same id#{id} not found");
            }

            return model;
        }
        protected ActionResult WViewRequest(string message, Func<ActionResult> action)
        {
            return WRequest<ActionResult>(message, action, (_) =>
            {
                return RedirectToAction("NotFound");
            });
        }
        protected TResult WRequest<TResult>(string message, Func<TResult> action, Func<Exception, TResult> error)
        {
            var result = default(TResult);

            try
            {
                result = action();

                _log.Info(Tag, message);
            }
            catch (InvalidRequestException exception)
            {
                _log.Error(Tag, exception);

                return error(exception);
            }

            return result;
        }
        protected ActionResult RedirectIndex()
        {
            return RedirectToAction("Index");
        }
    }
}

Films/Controllers/FilmsController.cs
using Films.Kernel.Context;
using Films.Kernel.Managers.Managers;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Films.Server.Controllers
{
    public class FilmsController : BaseController<FilmsManager, Film>
    {
        public override string Tag => "FilmsController";
        private ActorsManager _actors;

        public FilmsController() : base()
        {
            _actors = _factory.Create<ActorsManager>();
        }

        public override ActionResult Create()
        {
            ViewBag.AllActors = _actors.GetAll();

            return base.Create();
        }
        public override ActionResult Edit(long id)
        {
            ViewBag.AllActors = _actors.GetAll();

            return base.Edit(id);
        }
        public override ActionResult Update(Film element)
        {
            if (null != element.ActorIds)
            {
                element.Actors = _actors.GetAll().Where(a => element.ActorIds.Contains(a.Id)).ToList();
            }
            else
            {
                element.Actors = new List<Actor>();
            }

            return base.Update(element);
        }
    }
}

Films/Controllers/StartController.cs
using System.Web.Mvc;

namespace Films.Server.Controllers
{
    public class StartController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Films/Views/Actors/Details.cshtml
@model Films.Kernel.Context.Actor

<div>
    <h4>Actor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>FirstName</dt>
        <dd>@Model.FirstName</dd>

        <dt>LastName</dt>
        <dd>@Model.LastName</dd>

        <dt>MiddleName</dt>
        <dd>@Model.MiddleName</dd>

        <dt>Birth</dt>
        <dd>@Model.Birth</dd>

        <dt>Films</dt>
        <dd>
            @foreach (var film in Model.Films)
            {
                @film<br>
            }
        </dd>
    </dl>
</div>
<div>
    <div class="col-lg-3">
        <button class="btn-warning form-control" onclick="hrefActor('Edit', @Model.Id)">Edit</button>
    </div>

    <div class="col-lg-3">
        <button class="btn-success form-control" onclick="hrefActor('Index')">Back</button>
    </div>
</div>

Films/Views/Actors/Edit.cshtml
@model Films.Kernel.Context.Actor

@using (Html.BeginForm("Update", "Actors", new { Id = Model.Id }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Actor</h4>
        <hr />

        <div class="form-group">
            <label class="control-label col-md-2" for="FirstName">First name</label>
            <div class="col-md-10">
                <input name="FirstName" class="form-control" type="text" value="@Model.FirstName" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="LastName">Last name</label>
            <div class="col-md-10">
                <input name="LastName" class="form-control" type="text" value="@Model.LastName" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MiddleName">Middle name</label>
            <div class="col-md-10">
                <input name="MiddleName" class="form-control" type="text" value="@Model.MiddleName" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Birth">Birthday</label>
            <div class="col-md-10">
                <input name="Birth" class="form-control" type="date" value="@Model.Birth.ToString("yyyy-MM-dd")" required />
            </div>
        </div>

        <div>
            <div class="col-md-1">
                <button class="btn-success form-control" type="submit">Save</button>
            </div>
            <div class="col-md-1">
                <button class="btn-warning form-control" type="button" onclick="hrefActor('Index')">Cancel</button>
            </div>
        </div>
    </div>
}

Films/Views/Actors/Index.cshtml
@model IEnumerable<Films.Kernel.Context.Actor>

<div>
    <div class="col-md-10">
        <input class="form-control" id="search" onkeyup="search(6)" type="text" placeholder="Search" />
    </div>
    <div class="col-md-1">
        <button class="btn-success form-control" onclick="hrefActor('Create')">Create New</button>
    </div>
    <div class="col-md-1">
        <button class="btn-warning form-control" onclick="hrefStart()">Tables</button>
    </div>
</div><br /><br />

<table class="table" id="table">
    <tr>
        <th>Id</th>
        <th>FirstName</th>
        <th>LastName</th>
        <th>MiddleName</th>
        <th>Birth</th>
        <th>Films</th>
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@item.Id</td>
        <td>@item.FirstName</td>
        <td>@item.LastName</td>
        <td>@item.MiddleName</td>
        <td>@item.Birth</td>
        <td>
            @foreach (var film in item.Films)
            {
                @film<br>
            }
        </td>
        <td>
            <button class="btn-info form-control" onclick="hrefActor('Details', @item.Id)">Details</button>
        </td>
        <td>
            <button class="btn-warning form-control" onclick="hrefActor('Edit', @item.Id)">Edit</button>
        </td>
        <td>
            <button class="btn-danger form-control" onclick="hrefActor('Remove', @item.Id)">Remove</button>
        </td>
    </tr>
}

</table>

Films/Views/Films/Details.cshtml
@model Films.Kernel.Context.Film

<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>@Model.Name</dd>

        <dt>IssueDate</dt>
        <dd>@Model.IssueDate</dd>

        <dt>Country</dt>
        <dd>@Model.Country</dd>

        <dt>Genre</dt>
        <dd>@Model.Genre</dd>

        <dt>Duration</dt>
        <dd>@Model.Duration</dd>

        <dt>Actors</dt>
        <dd>
            @foreach (var actor in Model.Actors)
            {
                @actor<br>
            }
        </dd>
    </dl>
</div>
<div>
    <div class="col-lg-3">
        <button class="btn-warning form-control" onclick="hrefFilm('Edit', @Model.Id)">Edit</button>
    </div>

    <div class="col-lg-3">
        <button class="btn-success form-control" onclick="hrefFilm('Index')">Back</button>
    </div>
</div>

Films/Views/Films/Edit.cshtml
@model Films.Kernel.Context.Film
@using Films.Kernel.Context

@using (Html.BeginForm("Update", "Films", new { Id = Model.Id }, FormMethod.Post))
{
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Name</label>
            <div class="col-md-10">
                <input name="Name" class="form-control" type="text" value="@Model.Name" required/>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="IssueDate">Issue date</label>
            <div class="col-md-10">
                <input name="IssueDate" class="form-control" type="date" value="@Model.IssueDate.ToString("yyyy-MM-dd")" required/>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Country">Country</label>
            <div class="col-md-10">
                <input name="Country" class="form-control" type="text" value="@Model.Country" required/>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Genre">Genre</label>
            <div class="col-md-10">
                <input name="Genre" class="form-control" type="text" value="@Model.Genre" required/>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Duration">Duration</label>
            <div class="col-md-10">
                <input name="Duration" class="form-control"  type="number" min="0"value="@Model.Duration" required/>
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2" for="Actors">Actors</label>
            <div class="col-md-10">
                @foreach (var actor in ViewBag.AllActors as IEnumerable<Actor>)
                {
                    if (null != Model.Actors.FirstOrDefault(a => a.Id == actor.Id))
                    {
                        <label><input type="checkbox" name="ActorIds" value="@actor.Id" checked>@actor<br></label>
                    }
                    else
                    {
                        <label><input type="checkbox" name="ActorIds" value="@actor.Id">@actor<br></label>
                    }
                }
            </div>
        </div>

        <div>
            <div class="col-md-1">
                <button class="btn-success form-control" type="submit">Save</button>
            </div>
            <div class="col-md-1">
                <button class="btn-warning form-control" onclick="hrefFilm('Index')">Cancel</button>
            </div>
        </div>
    </div>
}

Films/Views/Films/Index.cshtml
@model IEnumerable<Films.Kernel.Context.Film>

<div>
    <div class="col-md-10">
        <input class="form-control" id="search" onkeyup="search(7)" type="text" placeholder="Search" />
    </div>
    <div class="col-md-1">
        <button class="btn-success form-control" onclick="hrefFilm('Create')">Create New</button>
    </div>
    <div class="col-md-1">
        <button class="btn-warning form-control" onclick="hrefStart()">Tables</button>
    </div>
</div><br /><br /><br />
<table class="table" id="films">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Issue date</th>
        <th>Country</th>
        <th>Genre</th>
        <th>Duration</th>
        <th>Actors</th>
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@item.Id</td>
        <td>@item.Name</td>
        <td>@item.IssueDate</td>
        <td>@item.Country</td>
        <td>@item.Genre</td>
        <td>@item.Duration</td>
        <td>
            @foreach (var actor in item.Actors)
            {
                @actor<br>
            }
        </td>
        <td>
            <button class="btn-info form-control" onclick="hrefFilm('Details', @item.Id)">Details</button>
        </td>
        <td>
            <button class="btn-warning form-control" onclick="hrefFilm('Edit', @item.Id)">Edit</button>
        </td>
        <td>
            <button class="btn-danger form-control" onclick="hrefFilm('Remove', @item.Id)">Remove</button>
        </td>
    </tr>
}
</table>

Films/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Films</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/frontend.js"></script>
</head>
<body>
    @RenderBody()

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Films/Views/Start/Index.cshtml
<div class="col-md-1">
    <button class="btn-success form-control" onclick="hrefFilm('Index')">Films</button>
</div>
<div class="col-md-1">
    <button class="btn-success form-control" onclick="hrefActor('Index')">Actors</button>
</div>